"""add resource requirements

Revision ID: 17653df4dd0a
Revises: 8dfefc8a5a68
Create Date: 2026-08-26 04:49:39.196080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17653df4dd0a'
down_revision = '8dfefc8a5a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['resource_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_requirements')
    # ### end Alembic commands ###
